import sys
from PyQt5.QtWidgets import QMainWindow, QApplication, QWidget, QAction, QTableWidget, QTableWidgetItem, QVBoxLayout
from PyQt5 import uic, QtCore
from PyQt5.QtGui import QIcon, QPixmap
import psycopg2
from psycopg2.extensions import adapt

qtCreatorFile = "yelpDatabaseUI.ui"
Ui_MainWindow, QtBaseClass = uic.loadUiType(qtCreatorFile)

class milestone1(QMainWindow):
    def __init__(self):
        super(milestone1, self).__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.loadStateList()
        self.ui.stateList.currentTextChanged.connect(self.stateChanged)
        self.ui.cityList.itemSelectionChanged.connect(self.cityChanged)
        self.ui.zipcodeList.itemSelectionChanged.connect(self.zipcodeChanged)
        self.ui.catlist.itemSelectionChanged.connect(self.catChanged)
        self.ui.loginname.textChanged.connect(self.getLoginNames)
        self.ui.loginlist.itemSelectionChanged.connect(self.displayInfo)
        self.ui.pushButton.clicked.connect(self.displaystats)
  
    def executeQuery(self,sql_str):
        try:
            conn = psycopg2.connect("dbname='yelpdb' user='postgres' host='localhost' password='admin'")
        except:
            print('Unable to connect to the database!')
        cur = conn.cursor()
        cur.execute(sql_str)
        conn.commit()
        result = cur.fetchall()
        conn.close()
        return result
    
    def loadStateList(self):
        self.ui.stateList.clear()
        sql_str = "SELECT distinct state FROM businesstable ORDER BY state;"
        try:
            results = self.executeQuery(sql_str)
            for row in results:
                    self.ui.stateList.addItem(row[0])
        except:
            print("Query failed")
        self.ui.stateList.setCurrentIndex(-1)
        self.ui.stateList.clearEditText()
    
    def stateChanged(self):
        self.ui.cityList.clear()
        self.ui.zipcodeList.clear()
        state = self.ui.stateList.currentText()
        if (self.ui.stateList.currentIndex()>=0): 
            sql_str = "SELECT distinct city FROM businesstable WHERE state ='" + state + "' ORDER BY city;"
            sql_str2 = "SELECT distinct postal_code FROM businesstable WHERE state ='" + state + "' ORDER BY postal_code;"
            try:
                results = self.executeQuery(sql_str)
                for row in results:
                    self.ui.cityList.addItem(row[0])  
                results = self.executeQuery(sql_str2)
                for row in results:
                    self.ui.zipcodeList.addItem(row[0]) 
            except:
                print("Query failed!")
            
            for i in reversed(range(self.ui.businessTable.rowCount())):
                self.ui.businessTable.removeRow(i)
            sql_str = "SELECT name, city, state, postal_code FROM businesstable WHERE state = '" +state+ "' ORDER BY name;"
            try:
                results = self.executeQuery(sql_str)
                style = "::section {""background-color: #f3f3f3; }"
                self.ui.businessTable.horizontalHeader().setStyleSheet(style)
                self.ui.businessTable.setColumnCount(len(results[0]))
                self.ui.businessTable.setRowCount(len(results))
                self.ui.businessTable.setHorizontalHeaderLabels(['Business Name', 'City', 'State', 'Zipcode'])
                self.ui.businessTable.resizeColumnsToContents()
                self.ui.businessTable.setColumnWidth(0,300)
                self.ui.businessTable.setColumnWidth(1,100)
                self.ui.businessTable.setColumnWidth(2,50)
                self.ui.businessTable.setColumnWidth(3,60)
                currentRowCount = 0
                for row in results:
                    for colCount in range (0,len(results[0])):
                        self.ui.businessTable.setItem(currentRowCount,colCount,QTableWidgetItem(row[colCount]))
                    currentRowCount +=1
            except:
                print("Query failed")
                
        
    def cityChanged(self):
        self.ui.zipcodeList.clear()
        if (self.ui.stateList.currentIndex() >=0) and (len(self.ui.cityList.selectedItems())>0):       
            state = self.ui.stateList.currentText()
            city = self.ui.cityList.selectedItems()[0].text()
            sql_str = "SELECT name, city, state, postal_code FROM businesstable WHERE state = '" +state+ "' AND city='" +city+ "' ORDER BY name;"
            sql_str2 = "SELECT distinct postal_code FROM businesstable WHERE state = '" +state+ "' AND city='" +city+ "' ORDER BY postal_code;"
            try:
                results = self.executeQuery(sql_str2)
                for row in results:
                    self.ui.zipcodeList.addItem(row[0])  
            except:
                print("Query failed!")
            try:
                results = self.executeQuery(sql_str)
                style = "::section {""background-color: #f3f3f3; }"
                self.ui.businessTable.horizontalHeader().setStyleSheet(style)
                self.ui.businessTable.setColumnCount(len(results[0]))
                self.ui.businessTable.setRowCount(len(results))
                self.ui.businessTable.setHorizontalHeaderLabels(['Business Name', 'City', 'State', 'Zipcode'])
                self.ui.businessTable.resizeColumnsToContents()
                self.ui.businessTable.setColumnWidth(0,300)
                self.ui.businessTable.setColumnWidth(1,100)
                self.ui.businessTable.setColumnWidth(2,50)
                self.ui.businessTable.setColumnWidth(3,60)
                currentRowCount = 0
                for row in results:
                    for colCount in range (0,len(results[0])):
                        self.ui.businessTable.setItem(currentRowCount,colCount,QTableWidgetItem(row[colCount]))
                    currentRowCount +=1
            except:
                print("Query failed")
    def zipcodeChanged(self):
        self.ui.numbus.clear()
        self.ui.categoryList.clear()
        self.ui.catlist.clear()
        if (self.ui.stateList.currentIndex() >=0) and (len(self.ui.cityList.selectedItems())>0) and (len(self.ui.zipcodeList.selectedItems())>0):       
            state = self.ui.stateList.currentText()
            city = self.ui.cityList.selectedItems()[0].text()
            zipcode = self.ui.zipcodeList.selectedItems()[0].text()
            sql_str = "SELECT name, city, state, postal_code FROM businesstable WHERE state = '" +state+ "' AND city='" +city+ "' AND postal_code='" +zipcode+ "' ORDER BY name;"
            sql_str2 = "SELECT postal_code, count(postal_code) FROM businesstable WHERE postal_code='" +zipcode+ "' GROUP BY postal_code;"
            sql_str3 = "select postal_code,category_name, count(*) from businesstable inner join categoriestable on businesstable.business_id = categoriestable.business_id where postal_code='" +zipcode+ "' group by postal_code,category_name order by count(*) desc;"
            sql_str4 = "SELECT category_name FROM businesstable inner join categoriestable on businesstable.business_id = categoriestable.business_id WHERE state = '" +state+ "' AND city='" +city+ "' AND postal_code='" +zipcode+ "' group by category_name ORDER BY category_name DESC;"
            
            count = self.executeQuery(sql_str2)
            self.ui.numbus.addItem(str(count[0][1])) 
            try:
                results = self.executeQuery(sql_str)
                style = "::section {""background-color: #f3f3f3; }"
                self.ui.businessTable.horizontalHeader().setStyleSheet(style)
                self.ui.businessTable.setColumnCount(len(results[0]))
                self.ui.businessTable.setRowCount(len(results))
                self.ui.businessTable.setHorizontalHeaderLabels(['Business Name', 'City', 'State', 'Zipcode'])
                self.ui.businessTable.resizeColumnsToContents()
                self.ui.businessTable.setColumnWidth(0,300)
                self.ui.businessTable.setColumnWidth(1,100)
                self.ui.businessTable.setColumnWidth(2,50)
                self.ui.businessTable.setColumnWidth(3,60)
                currentRowCount = 0
                for row in results:
                    for colCount in range (0,len(results[0])):
                        self.ui.businessTable.setItem(currentRowCount,colCount,QTableWidgetItem(row[colCount]))
                    currentRowCount +=1
            except:
                print("Query failed")
            try:
                results = self.executeQuery(sql_str3)
                for row in results:
                    self.ui.categoryList.addItem(str(row[1])) 
            except:
                print("Query failed")                
            try:
                results = self.executeQuery(sql_str4)
                for row in results:
                    self.ui.catlist.addItem(str(row[0])) 
            except:
                print("Query failed")
                
    def catChanged(self):
        if (self.ui.stateList.currentIndex() >=0) and (len(self.ui.cityList.selectedItems())>0) and (len(self.ui.zipcodeList.selectedItems())>0) and (len(self.ui.catlist.selectedItems())>0):       
            state = self.ui.stateList.currentText()
            city = self.ui.cityList.selectedItems()[0].text()
            zipcode = self.ui.zipcodeList.selectedItems()[0].text()
            category = self.ui.catlist.selectedItems()[0].text()
            sql_str = "SELECT name, city, state, postal_code FROM businesstable inner join categoriestable on businesstable.business_id = categoriestable.business_id WHERE state = '" +state+ "' AND city='" +city+ "' AND postal_code='" +zipcode+ "' AND category_name= '"+category+"' ORDER BY name;"
            try:
                results = self.executeQuery(sql_str)
                style = "::section {""background-color: #f3f3f3; }"
                self.ui.businessTable.horizontalHeader().setStyleSheet(style)
                self.ui.businessTable.setColumnCount(len(results[0]))
                self.ui.businessTable.setRowCount(len(results))
                self.ui.businessTable.setHorizontalHeaderLabels(['Business Name', 'City', 'State', 'Zipcode'])
                self.ui.businessTable.resizeColumnsToContents()
                self.ui.businessTable.setColumnWidth(0,300)
                self.ui.businessTable.setColumnWidth(1,100)
                self.ui.businessTable.setColumnWidth(2,50)
                self.ui.businessTable.setColumnWidth(3,60)
                currentRowCount = 0
                for row in results:
                    for colCount in range (0,len(results[0])):
                        self.ui.businessTable.setItem(currentRowCount,colCount,QTableWidgetItem(row[colCount]))
                    currentRowCount +=1
            except:
                print("Query failed")
    

            

            
    def getLoginNames(self):
        self.ui.loginlist.clear()
        loginname = self.ui.loginname.text()
        sql_str = "SELECT user_id FROM usertable WHERE name LIKE '%"+loginname+"%' ORDER BY user_id;"
        try:
            results = self.executeQuery(sql_str)

            for row in results:
                self.ui.loginlist.addItem(row[0]) 

        except:
            print("Query failed!")   
            
    def displayInfo(self):
        loginlist = self.ui.loginlist.selectedItems()[0].text()
        loginlist = str(adapt(loginlist))[1:-1]
        sql_str = "SELECT name,average_stars,yelping_since,funny,cool,useful FROM usertable WHERE user_id = '"+loginlist+"';"
        sql_str2 = "select name,average_stars,fans,tipcount,yelping_since from usertable, (select * from friendtable where user_id = '"+loginlist+"') as t2 where usertable.user_id = t2.friend_id;"
        sql_str3 = "select t4.name, businesstable.name, businesstable.city, t4.date, t4.text from businesstable, (select usertable.name,  tiptable.text, tiptable.business_id, t3.date from tiptable, usertable, (select tiptable.user_id, MAX(date) as date from tiptable, (select * from friendtable where user_id = '"+loginlist+"') as t2 where tiptable.user_id = t2.friend_id group by tiptable.user_id order by tiptable.user_id) as t3 where usertable.user_id = t3.user_id AND t3.user_id = tiptable.user_id AND t3.date = tiptable.date ) as t4 where businesstable.business_id = t4.business_id;"
        sql_str4 = "SELECT name,average_stars,fans, tipcount, yelping_since from usertable, (select friendtable.friend_id from friendtable, (select friend_id from friendtable where user_id = '"+loginlist+"') as t1  where friendtable.user_id = t1.friend_id AND friendtable.friend_id NOT IN (select friend_id from friendtable where user_id = '"+loginlist+"') AND friendtable.friend_id != '"+loginlist+"'  group by friendtable.friend_id having count(*) > 2 order by count(*) desc) as t2  where t2.friend_id = usertable.user_id;"
        try:
            results = self.executeQuery(sql_str)
            self.ui.namebox.setText(results[0][0])
            self.ui.starsbox.setText(results[0][1])
            self.ui.sincebox.setText(results[0][2])
            self.ui.funnybox.setText(results[0][3])
            self.ui.coolbox.setText(results[0][4])
            self.ui.usefulbox.setText(results[0][5])
        except:
            print("Query failed!") 
        for i in reversed(range(self.ui.friendtable.rowCount())):
            self.ui.friendtable.removeRow(i)
        try:
            results = self.executeQuery(sql_str2)
            style = "::section {""background-color: #f3f3f3; }"
            self.ui.friendtable.horizontalHeader().setStyleSheet(style)
            self.ui.friendtable.setColumnCount(len(results[0]))
            self.ui.friendtable.setRowCount(len(results))
            self.ui.friendtable.setHorizontalHeaderLabels(['Friend Name', 'Avg Stars', 'Fans', 'Tip Count', 'Yelping Since'])
            self.ui.friendtable.resizeColumnsToContents()
            self.ui.friendtable.setColumnWidth(0,100)
            self.ui.friendtable.setColumnWidth(1,40)
            self.ui.friendtable.setColumnWidth(2,50)
            self.ui.friendtable.setColumnWidth(3,60)
            self.ui.friendtable.setColumnWidth(4,60)
            currentRowCount = 0
            for row in results:
                for colCount in range (0,len(results[0])):
                    self.ui.friendtable.setItem(currentRowCount,colCount,QTableWidgetItem(row[colCount]))
                currentRowCount +=1
        except:
            print("Query failed")
        for i in reversed(range(self.ui.latesttable.rowCount())):
            self.ui.latesttable.removeRow(i)
        try:
            results = self.executeQuery(sql_str3)
            style = "::section {""background-color: #f3f3f3; }"
            self.ui.latesttable.horizontalHeader().setStyleSheet(style)
            self.ui.latesttable.setColumnCount(len(results[0]))
            self.ui.latesttable.setRowCount(len(results))
            self.ui.latesttable.setHorizontalHeaderLabels(['Friend Name', 'Business', 'City', 'Date', 'Review'])
            self.ui.latesttable.resizeColumnsToContents()
            self.ui.latesttable.setColumnWidth(0,100)
            self.ui.latesttable.setColumnWidth(1,100)
            self.ui.latesttable.setColumnWidth(2,80)
            self.ui.latesttable.setColumnWidth(3,60)
            self.ui.latesttable.setColumnWidth(4,60)
            currentRowCount = 0
            for row in results:
                for colCount in range (0,len(results[0])):
                    self.ui.latesttable.setItem(currentRowCount,colCount,QTableWidgetItem(row[colCount]))
                currentRowCount +=1
        except:
            print("Query failed")
        for i in reversed(range(self.ui.suggestiontable.rowCount())):
            self.ui.suggestiontable.removeRow(i)
        try:
            results = self.executeQuery(sql_str4)
            style = "::section {""background-color: #f3f3f3; }"
            self.ui.suggestiontable.horizontalHeader().setStyleSheet(style)
            self.ui.suggestiontable.setColumnCount(len(results[0]))
            self.ui.suggestiontable.setRowCount(len(results))
            self.ui.suggestiontable.setHorizontalHeaderLabels(['Name', 'Avg Stars', 'Fans', 'Tip Count', 'Yelping Since'])
            self.ui.suggestiontable.resizeColumnsToContents()
            self.ui.suggestiontable.setColumnWidth(0,100)
            self.ui.suggestiontable.setColumnWidth(1,40)
            self.ui.suggestiontable.setColumnWidth(2,50)
            self.ui.suggestiontable.setColumnWidth(3,60)
            self.ui.suggestiontable.setColumnWidth(4,60)
            currentRowCount = 0
            for row in results:
                for colCount in range (0,len(results[0])):
                    self.ui.suggestiontable.setItem(currentRowCount,colCount,QTableWidgetItem(row[colCount]))
                currentRowCount +=1
        except:
            print("Query failed")
        
    def displaystats(self):
        if (len(self.ui.zipcodeList.selectedItems())>0) and (len(self.ui.catlist.selectedItems())>0):
            zipcode = self.ui.zipcodeList.selectedItems()[0].text()
            category = self.ui.catlist.selectedItems()[0].text()
            sql_str = """
            select name, numcheckins, numtips, t1.score
            from (
            	select t1.business_id, ((c1+c2+c3)::FLOAT/3)::INTEGER as score
            	from (
            	SELECT business_id, (((count(*)::FLOAT-1)/(32-1))*100)::INTEGER as c1
            	FROM attributestable 
            	WHERE value != 'False'
            	GROUP BY business_id
            	ORDER BY count(*) desc
            	) as t1,
            	(
            	SELECT business_id, (((count(*)::FLOAT-1)/(1000-1))*100)::INTEGER as c2
            	FROM checkintable
            	GROUP BY business_id
            	ORDER BY count(*) desc
            	) as t2,
            	(
            	select business_id, (((count(*)::FLOAT-1)/(1472-1))*100)::INTEGER as c3
            	from tiptable
            	group by business_id
            	order by count(*) desc
            	) as t3
            	where t1.business_id = t2.business_id AND t3.business_id = t2.business_id
            	order by score desc
            ) as t1 ,
            businesstable, categoriestable
            where t1.business_id = businesstable.business_id and categoriestable.business_id = t1.business_id  and  businesstable.postal_code='""" +zipcode+ """' AND categoriestable.category_name= '"""+category+"""' 
            ORDER BY t1.score desc;"""
            sql_str2 = """
            select name, address, t1.score
            from (
            	SELECT business_id, (((count(text)::float*1-1)/(424-1))*100)::INTEGER as score 
            	FROM tiptable
            	WHERE text LIKE '%a+%'
            	OR text LIKE '%abound%'
            	OR text LIKE '%abounds%'
            	OR text LIKE '%abundance%'
            	OR text LIKE '%abundant%'
            	OR text LIKE '%accessable%'
            	OR text LIKE '%accessible%'
            	OR text LIKE '%acclaim%'
            	OR text LIKE '%acclaimed%'
            	OR text LIKE '%acclamation%'
            	OR text LIKE '%accolade%'
            	OR text LIKE '%accolades%'
            	OR text LIKE '%accommodative%'
            	OR text LIKE '%accomodative%'
            	OR text LIKE '%accomplish%'
            	OR text LIKE '%accomplished%'
            	OR text LIKE '%accomplishment%'
            	OR text LIKE '%accomplishments%'
            	OR text LIKE '%accurate%'
            	OR text LIKE '%accurately%'
            	OR text LIKE '%achievable%'
            	OR text LIKE '%achievement%'
            	OR text LIKE '%achievements%'
            	OR text LIKE '%achievible%'
            	OR text LIKE '%acumen%'
            	OR text LIKE '%adaptable%'
            	OR text LIKE '%adaptive%'
            	OR text LIKE '%adequate%'
            	OR text LIKE '%adjustable%'
            	OR text LIKE '%admirable%'
            	OR text LIKE '%admirably%'
            	OR text LIKE '%admiration%'
            	OR text LIKE '%admire%'
            	OR text LIKE '%admirer%'
            	OR text LIKE '%admiring%'
            	OR text LIKE '%admiringly%'
            	OR text LIKE '%adorable%'
            	OR text LIKE '%adore%'
            	OR text LIKE '%adored%'
            	OR text LIKE '%adorer%'
            	OR text LIKE '%adoring%'
            	OR text LIKE '%adoringly%'
            	OR text LIKE '%adroit%'
            	OR text LIKE '%adroitly%'
            	OR text LIKE '%adulate%'
            	OR text LIKE '%adulation%'
            	OR text LIKE '%adulatory%'
            	OR text LIKE '%advanced%'
            	OR text LIKE '%advantage%'
            	OR text LIKE '%advantageous%'
            	OR text LIKE '%advantageously%'
            	OR text LIKE '%advantages%'
            	OR text LIKE '%adventuresome%'
            	OR text LIKE '%adventurous%'
            	OR text LIKE '%advocate%'
            	OR text LIKE '%advocated%'
            	OR text LIKE '%advocates%'
            	OR text LIKE '%affability%'
            	OR text LIKE '%affable%'
            	OR text LIKE '%affably%'
            	OR text LIKE '%affectation%'
            	OR text LIKE '%affection%'
            	OR text LIKE '%affectionate%'
            	OR text LIKE '%affinity%'
            	OR text LIKE '%affirm%'
            	OR text LIKE '%affirmation%'
            	OR text LIKE '%affirmative%'
            	OR text LIKE '%affluence%'
            	OR text LIKE '%affluent%'
            	OR text LIKE '%afford%'
            	OR text LIKE '%affordable%'
            	OR text LIKE '%affordably%'
            	OR text LIKE '%afordable%'
            	OR text LIKE '%agile%'
            	OR text LIKE '%agilely%'
            	OR text LIKE '%agility%'
            	OR text LIKE '%agreeable%'
            	OR text LIKE '%agreeableness%'
            	OR text LIKE '%agreeably%'
            	OR text LIKE '%all-around%'
            	OR text LIKE '%alluring%'
            	OR text LIKE '%alluringly%'
            	OR text LIKE '%altruistic%'
            	OR text LIKE '%altruistically%'
            	OR text LIKE '%amaze%'
            	OR text LIKE '%amazed%'
            	OR text LIKE '%amazement%'
            	OR text LIKE '%amazes%'
            	OR text LIKE '%amazing%'
            	OR text LIKE '%amazingly%'
            	OR text LIKE '%ambitious%'
            	OR text LIKE '%ambitiously%'
            	OR text LIKE '%ameliorate%'
            	OR text LIKE '%amenable%'
            	OR text LIKE '%amenity%'
            	OR text LIKE '%amiability%'
            	OR text LIKE '%amiabily%'
            	OR text LIKE '%amiable%'
            	OR text LIKE '%amicability%'
            	OR text LIKE '%amicable%'
            	OR text LIKE '%amicably%'
            	OR text LIKE '%amity%'
            	OR text LIKE '%ample%'
            	OR text LIKE '%amply%'
            	OR text LIKE '%amuse%'
            	OR text LIKE '%amusing%'
            	OR text LIKE '%amusingly%'
            	OR text LIKE '%angel%'
            	OR text LIKE '%angelic%'
            	OR text LIKE '%apotheosis%'
            	OR text LIKE '%appeal%'
            	OR text LIKE '%appealing%'
            	OR text LIKE '%applaud%'
            	OR text LIKE '%appreciable%'
            	OR text LIKE '%appreciate%'
            	OR text LIKE '%appreciated%'
            	OR text LIKE '%appreciates%'
            	OR text LIKE '%appreciative%'
            	OR text LIKE '%appreciatively%'
            	OR text LIKE '%appropriate%'
            	OR text LIKE '%approval%'
            	OR text LIKE '%approve%'
            	OR text LIKE '%ardent%'
            	OR text LIKE '%ardently%'
            	OR text LIKE '%ardor%'
            	OR text LIKE '%articulate%'
            	OR text LIKE '%aspiration%'
            	OR text LIKE '%aspirations%'
            	OR text LIKE '%aspire%'
            	OR text LIKE '%assurance%'
            	OR text LIKE '%assurances%'
            	OR text LIKE '%assure%'
            	OR text LIKE '%assuredly%'
            	OR text LIKE '%assuring%'
            	OR text LIKE '%astonish%'
            	OR text LIKE '%astonished%'
            	OR text LIKE '%astonishing%'
            	OR text LIKE '%astonishingly%'
            	OR text LIKE '%astonishment%'
            	OR text LIKE '%astound%'
            	OR text LIKE '%astounded%'
            	OR text LIKE '%astounding%'
            	OR text LIKE '%astoundingly%'
            	OR text LIKE '%astutely%'
            	OR text LIKE '%attentive%'
            	OR text LIKE '%attraction%'
            	OR text LIKE '%attractive%'
            	OR text LIKE '%attractively%'
            	OR text LIKE '%attune%'
            	OR text LIKE '%audible%'
            	OR text LIKE '%audibly%'
            	OR text LIKE '%auspicious%'
            	OR text LIKE '%authentic%'
            	OR text LIKE '%authoritative%'
            	OR text LIKE '%autonomous%'
            	OR text LIKE '%available%'
            	OR text LIKE '%aver%'
            	OR text LIKE '%avid%'
            	OR text LIKE '%avidly%'
            	OR text LIKE '%award%'
            	OR text LIKE '%awarded%'
            	OR text LIKE '%awards%'
            	OR text LIKE '%awe%'
            	OR text LIKE '%awed%'
            	OR text LIKE '%awesome%'
            	OR text LIKE '%awesomely%'
            	OR text LIKE '%awesomeness%'
            	OR text LIKE '%awestruck%'
            	OR text LIKE '%awsome%'
            	OR text LIKE '%backbone%'
            	OR text LIKE '%balanced%'
            	OR text LIKE '%bargain%'
            	OR text LIKE '%beauteous%'
            	OR text LIKE '%beautiful%'
            	OR text LIKE '%beautifullly%'
            	OR text LIKE '%beautifully%'
            	OR text LIKE '%beautify%'
            	OR text LIKE '%beauty%'
            	OR text LIKE '%beckon%'
            	OR text LIKE '%beckoned%'
            	OR text LIKE '%beckoning%'
            	OR text LIKE '%beckons%'
            	OR text LIKE '%believable%'
            	OR text LIKE '%believeable%'
            	OR text LIKE '%beloved%'
            	OR text LIKE '%benefactor%'
            	OR text LIKE '%beneficent%'
            	OR text LIKE '%beneficial%'
            	OR text LIKE '%beneficially%'
            	OR text LIKE '%beneficiary%'
            	OR text LIKE '%benefit%'
            	OR text LIKE '%benefits%'
            	OR text LIKE '%benevolence%'
            	OR text LIKE '%benevolent%'
            	OR text LIKE '%benifits%'
            	OR text LIKE '%best%'
            	OR text LIKE '%best-known%'
            	OR text LIKE '%best-performing%'
            	OR text LIKE '%best-selling%'
            	OR text LIKE '%better%'
            	OR text LIKE '%better-known%'
            	OR text LIKE '%better-than-expected%'
            	OR text LIKE '%beutifully%'
            	OR text LIKE '%blameless%'
            	OR text LIKE '%bless%'
            	OR text LIKE '%blessing%'
            	OR text LIKE '%bliss%'
            	OR text LIKE '%blissful%'
            	OR text LIKE '%blissfully%'
            	OR text LIKE '%blithe%'
            	OR text LIKE '%blockbuster%'
            	OR text LIKE '%bloom%'
            	OR text LIKE '%blossom%'
            	OR text LIKE '%bolster%'
            	OR text LIKE '%bonny%'
            	OR text LIKE '%bonus%'
            	OR text LIKE '%bonuses%'
            	OR text LIKE '%boom%'
            	OR text LIKE '%booming%'
            	OR text LIKE '%boost%'
            	OR text LIKE '%boundless%'
            	OR text LIKE '%bountiful%'
            	OR text LIKE '%brainiest%'
            	OR text LIKE '%brainy%'
            	OR text LIKE '%brand-new%'
            	OR text LIKE '%brave%'
            	OR text LIKE '%bravery%'
            	OR text LIKE '%bravo%'
            	OR text LIKE '%breakthrough%'
            	OR text LIKE '%breakthroughs%'
            	OR text LIKE '%breathlessness%'
            	OR text LIKE '%breathtaking%'
            	OR text LIKE '%breathtakingly%'
            	OR text LIKE '%breeze%'
            	OR text LIKE '%bright%'
            	OR text LIKE '%brighten%'
            	OR text LIKE '%brighter%'
            	OR text LIKE '%brightest%'
            	OR text LIKE '%brilliance%'
            	OR text LIKE '%brilliances%'
            	OR text LIKE '%brilliant%'
            	OR text LIKE '%brilliantly%'
            	OR text LIKE '%brisk%'
            	OR text LIKE '%brotherly%'
            	OR text LIKE '%bullish%'
            	OR text LIKE '%buoyant%'
            	OR text LIKE '%cajole%'
            	OR text LIKE '%calm%'
            	OR text LIKE '%calming%'
            	OR text LIKE '%calmness%'
            	OR text LIKE '%capability%'
            	OR text LIKE '%capable%'
            	OR text LIKE '%capably%'
            	OR text LIKE '%captivate%'
            	OR text LIKE '%captivating%'
            	OR text LIKE '%carefree%'
            	OR text LIKE '%cashback%'
            	OR text LIKE '%cashbacks%'
            	OR text LIKE '%catchy%'
            	OR text LIKE '%celebrate%'
            	OR text LIKE '%celebrated%'
            	OR text LIKE '%celebration%'
            	OR text LIKE '%celebratory%'
            	OR text LIKE '%champ%'
            	OR text LIKE '%champion%'
            	OR text LIKE '%charisma%'
            	OR text LIKE '%charismatic%'
            	OR text LIKE '%charitable%'
            	OR text LIKE '%charm%'
            	OR text LIKE '%charming%'
            	OR text LIKE '%charmingly%'
            	OR text LIKE '%chaste%'
            	OR text LIKE '%cheaper%'
            	OR text LIKE '%cheapest%'
            	OR text LIKE '%cheer%'
            	OR text LIKE '%cheerful%'
            	OR text LIKE '%cheery%'
            	OR text LIKE '%cherish%'
            	OR text LIKE '%cherished%'
            	OR text LIKE '%cherub%'
            	OR text LIKE '%chic%'
            	OR text LIKE '%chivalrous%'
            	OR text LIKE '%chivalry%'
            	OR text LIKE '%civility%'
            	OR text LIKE '%civilize%'
            	OR text LIKE '%clarity%'
            	OR text LIKE '%classic%'
            	OR text LIKE '%classy%'
            	OR text LIKE '%clean%'
            	OR text LIKE '%cleaner%'
            	OR text LIKE '%cleanest%'
            	OR text LIKE '%cleanliness%'
            	OR text LIKE '%cleanly%'
            	OR text LIKE '%clear%'
            	OR text LIKE '%clear-cut%'
            	OR text LIKE '%cleared%'
            	OR text LIKE '%clearer%'
            	OR text LIKE '%clearly%'
            	OR text LIKE '%clears%'
            	OR text LIKE '%clever%'
            	OR text LIKE '%cleverly%'
            	OR text LIKE '%cohere%'
            	OR text LIKE '%coherence%'
            	OR text LIKE '%coherent%'
            	OR text LIKE '%cohesive%'
            	OR text LIKE '%colorful%'
            	OR text LIKE '%comely%'
            	OR text LIKE '%comfort%'
            	OR text LIKE '%comfortable%'
            	OR text LIKE '%comfortably%'
            	OR text LIKE '%comforting%'
            	OR text LIKE '%comfy%'
            	OR text LIKE '%commend%'
            	OR text LIKE '%commendable%'
            	OR text LIKE '%commendably%'
            	OR text LIKE '%commitment%'
            	OR text LIKE '%commodious%'
            	OR text LIKE '%compact%'
            	OR text LIKE '%compactly%'
            	OR text LIKE '%compassion%'
            	OR text LIKE '%compassionate%'
            	OR text LIKE '%compatible%'
            	OR text LIKE '%competitive%'
            	OR text LIKE '%complement%'
            	OR text LIKE '%complementary%'
            	OR text LIKE '%complemented%'
            	OR text LIKE '%complements%'
            	OR text LIKE '%compliant%'
            	OR text LIKE '%compliment%'
            	OR text LIKE '%complimentary%'
            	OR text LIKE '%comprehensive%'
            	OR text LIKE '%conciliate%'
            	OR text LIKE '%conciliatory%'
            	OR text LIKE '%concise%'
            	OR text LIKE '%confidence%'
            	OR text LIKE '%confident%'
            	OR text LIKE '%congenial%'
            	OR text LIKE '%congratulate%'
            	OR text LIKE '%congratulation%'
            	OR text LIKE '%congratulations%'
            	OR text LIKE '%congratulatory%'
            	OR text LIKE '%conscientious%'
            	OR text LIKE '%considerate%'
            	OR text LIKE '%consistent%'
            	OR text LIKE '%consistently%'
            	OR text LIKE '%constructive%'
            	OR text LIKE '%consummate%'
            	OR text LIKE '%contentment%'
            	OR text LIKE '%continuity%'
            	OR text LIKE '%contrasty%'
            	OR text LIKE '%contribution%'
            	OR text LIKE '%convenience%'
            	OR text LIKE '%convenient%'
            	OR text LIKE '%conveniently%'
            	OR text LIKE '%convience%'
            	OR text LIKE '%convienient%'
            	OR text LIKE '%convient%'
            	OR text LIKE '%convincing%'
            	OR text LIKE '%convincingly%'
            	OR text LIKE '%cool%'
            	OR text LIKE '%coolest%'
            	OR text LIKE '%cooperative%'
            	OR text LIKE '%cooperatively%'
            	OR text LIKE '%cornerstone%'
            	OR text LIKE '%correct%'
            	OR text LIKE '%correctly%'
            	OR text LIKE '%cost-effective%'
            	OR text LIKE '%cost-saving%'
            	OR text LIKE '%counter-attack%'
            	OR text LIKE '%counter-attacks%'
            	OR text LIKE '%courage%'
            	OR text LIKE '%courageous%'
            	OR text LIKE '%courageously%'
            	OR text LIKE '%courageousness%'
            	OR text LIKE '%courteous%'
            	OR text LIKE '%courtly%'
            	OR text LIKE '%covenant%'
            	OR text LIKE '%cozy%'
            	OR text LIKE '%creative%'
            	OR text LIKE '%credence%'
            	OR text LIKE '%credible%'
            	OR text LIKE '%crisp%'
            	OR text LIKE '%crisper%'
            	OR text LIKE '%cure%'
            	OR text LIKE '%cure-all%'
            	OR text LIKE '%cushy%'
            	OR text LIKE '%cute%'
            	OR text LIKE '%cuteness%'
            	OR text LIKE '%danke%'
            	OR text LIKE '%danken%'
            	OR text LIKE '%daring%'
            	OR text LIKE '%daringly%'
            	OR text LIKE '%darling%'
            	OR text LIKE '%dashing%'
            	OR text LIKE '%dauntless%'
            	OR text LIKE '%dawn%'
            	OR text LIKE '%dazzle%'
            	OR text LIKE '%dazzled%'
            	OR text LIKE '%dazzling%'
            	OR text LIKE '%dead-cheap%'
            	OR text LIKE '%dead-on%'
            	OR text LIKE '%decency%'
            	OR text LIKE '%decent%'
            	OR text LIKE '%decisive%'
            	OR text LIKE '%decisiveness%'
            	OR text LIKE '%dedicated%'
            	OR text LIKE '%defeat%'
            	OR text LIKE '%defeated%'
            	OR text LIKE '%defeating%'
            	OR text LIKE '%defeats%'
            	OR text LIKE '%defender%'
            	OR text LIKE '%deference%'
            	OR text LIKE '%deft%'
            	OR text LIKE '%deginified%'
            	OR text LIKE '%delectable%'
            	OR text LIKE '%delicacy%'
            	OR text LIKE '%delicate%'
            	OR text LIKE '%delicious%'
            	OR text LIKE '%delight%'
            	OR text LIKE '%delighted%'
            	OR text LIKE '%delightful%'
            	OR text LIKE '%delightfully%'
            	OR text LIKE '%delightfulness%'
            	OR text LIKE '%dependable%'
            	OR text LIKE '%dependably%'
            	OR text LIKE '%deservedly%'
            	OR text LIKE '%deserving%'
            	OR text LIKE '%desirable%'
            	OR text LIKE '%desiring%'
            	OR text LIKE '%desirous%'
            	OR text LIKE '%destiny%'
            	OR text LIKE '%detachable%'
            	OR text LIKE '%devout%'
            	OR text LIKE '%dexterous%'
            	OR text LIKE '%dexterously%'
            	OR text LIKE '%dextrous%'
            	OR text LIKE '%dignified%'
            	OR text LIKE '%dignify%'
            	OR text LIKE '%dignity%'
            	OR text LIKE '%diligence%'
            	OR text LIKE '%diligent%'
            	OR text LIKE '%diligently%'
            	OR text LIKE '%diplomatic%'
            	OR text LIKE '%dirt-cheap%'
            	OR text LIKE '%distinction%'
            	OR text LIKE '%distinctive%'
            	OR text LIKE '%distinguished%'
            	OR text LIKE '%diversified%'
            	OR text LIKE '%divine%'
            	OR text LIKE '%divinely%'
            	OR text LIKE '%dominate%'
            	OR text LIKE '%dominated%'
            	OR text LIKE '%dominates%'
            	OR text LIKE '%dote%'
            	OR text LIKE '%dotingly%'
            	OR text LIKE '%doubtless%'
            	OR text LIKE '%dreamland%'
            	OR text LIKE '%dumbfounded%'
            	OR text LIKE '%dumbfounding%'
            	OR text LIKE '%dummy-proof%'
            	OR text LIKE '%durable%'
            	OR text LIKE '%dynamic%'
            	OR text LIKE '%eager%'
            	OR text LIKE '%eagerly%'
            	OR text LIKE '%eagerness%'
            	OR text LIKE '%earnest%'
            	OR text LIKE '%earnestly%'
            	OR text LIKE '%earnestness%'
            	OR text LIKE '%ease%'
            	OR text LIKE '%eased%'
            	OR text LIKE '%eases%'
            	OR text LIKE '%easier%'
            	OR text LIKE '%easiest%'
            	OR text LIKE '%easiness%'
            	OR text LIKE '%easing%'
            	OR text LIKE '%easy%'
            	OR text LIKE '%easy-to-use%'
            	OR text LIKE '%easygoing%'
            	OR text LIKE '%ebullience%'
            	OR text LIKE '%ebullient%'
            	OR text LIKE '%ebulliently%'
            	OR text LIKE '%ecenomical%'
            	OR text LIKE '%economical%'
            	OR text LIKE '%ecstasies%'
            	OR text LIKE '%ecstasy%'
            	OR text LIKE '%ecstatic%'
            	OR text LIKE '%ecstatically%'
            	OR text LIKE '%edify%'
            	OR text LIKE '%educated%'
            	OR text LIKE '%effective%'
            	OR text LIKE '%effectively%'
            	OR text LIKE '%effectiveness%'
            	OR text LIKE '%effectual%'
            	OR text LIKE '%efficacious%'
            	OR text LIKE '%efficient%'
            	OR text LIKE '%efficiently%'
            	OR text LIKE '%effortless%'
            	OR text LIKE '%effortlessly%'
            	OR text LIKE '%effusion%'
            	OR text LIKE '%effusive%'
            	OR text LIKE '%effusively%'
            	OR text LIKE '%effusiveness%'
            	OR text LIKE '%elan%'
            	OR text LIKE '%elate%'
            	OR text LIKE '%elated%'
            	OR text LIKE '%elatedly%'
            	OR text LIKE '%elation%'
            	OR text LIKE '%electrify%'
            	OR text LIKE '%elegance%'
            	OR text LIKE '%elegant%'
            	OR text LIKE '%elegantly%'
            	OR text LIKE '%elevate%'
            	OR text LIKE '%elite%'
            	OR text LIKE '%eloquence%'
            	OR text LIKE '%eloquent%'
            	OR text LIKE '%eloquently%'
            	OR text LIKE '%embolden%'
            	OR text LIKE '%eminence%'
            	OR text LIKE '%eminent%'
            	OR text LIKE '%empathize%'
            	OR text LIKE '%empathy%'
            	OR text LIKE '%empower%'
            	OR text LIKE '%empowerment%'
            	OR text LIKE '%enchant%'
            	OR text LIKE '%enchanted%'
            	OR text LIKE '%enchanting%'
            	OR text LIKE '%enchantingly%'
            	OR text LIKE '%encourage%'
            	OR text LIKE '%encouragement%'
            	OR text LIKE '%encouraging%'
            	OR text LIKE '%encouragingly%'
            	OR text LIKE '%endear%'
            	OR text LIKE '%endearing%'
            	OR text LIKE '%endorse%'
            	OR text LIKE '%endorsed%'
            	OR text LIKE '%endorsement%'
            	OR text LIKE '%endorses%'
            	OR text LIKE '%endorsing%'
            	OR text LIKE '%energetic%'
            	OR text LIKE '%energize%'
            	OR text LIKE '%energy-efficient%'
            	OR text LIKE '%energy-saving%'
            	OR text LIKE '%engaging%'
            	OR text LIKE '%engrossing%'
            	OR text LIKE '%enhance%'
            	OR text LIKE '%enhanced%'
            	OR text LIKE '%enhancement%'
            	OR text LIKE '%enhances%'
            	OR text LIKE '%enjoy%'
            	OR text LIKE '%enjoyable%'
            	OR text LIKE '%enjoyably%'
            	OR text LIKE '%enjoyed%'
            	OR text LIKE '%enjoying%'
            	OR text LIKE '%enjoyment%'
            	OR text LIKE '%enjoys%'
            	OR text LIKE '%enlighten%'
            	OR text LIKE '%enlightenment%'
            	OR text LIKE '%enliven%'
            	OR text LIKE '%ennoble%'
            	OR text LIKE '%enough%'
            	OR text LIKE '%enrapt%'
            	OR text LIKE '%enrapture%'
            	OR text LIKE '%enraptured%'
            	OR text LIKE '%enrich%'
            	OR text LIKE '%enrichment%'
            	OR text LIKE '%enterprising%'
            	OR text LIKE '%entertain%'
            	OR text LIKE '%entertaining%'
            	OR text LIKE '%entertains%'
            	OR text LIKE '%enthral%'
            	OR text LIKE '%enthrall%'
            	OR text LIKE '%enthralled%'
            	OR text LIKE '%enthuse%'
            	OR text LIKE '%enthusiasm%'
            	OR text LIKE '%enthusiast%'
            	OR text LIKE '%enthusiastic%'
            	OR text LIKE '%enthusiastically%'
            	OR text LIKE '%entice%'
            	OR text LIKE '%enticed%'
            	OR text LIKE '%enticing%'
            	OR text LIKE '%enticingly%'
            	OR text LIKE '%entranced%'
            	OR text LIKE '%entrancing%'
            	OR text LIKE '%entrust%'
            	OR text LIKE '%enviable%'
            	OR text LIKE '%enviably%'
            	OR text LIKE '%envious%'
            	OR text LIKE '%enviously%'
            	OR text LIKE '%enviousness%'
            	OR text LIKE '%envy%'
            	OR text LIKE '%equitable%'
            	OR text LIKE '%ergonomical%'
            	OR text LIKE '%err-free%'
            	OR text LIKE '%erudite%'
            	OR text LIKE '%ethical%'
            	OR text LIKE '%eulogize%'
            	OR text LIKE '%euphoria%'
            	OR text LIKE '%euphoric%'
            	OR text LIKE '%euphorically%'
            	OR text LIKE '%evaluative%'
            	OR text LIKE '%evenly%'
            	OR text LIKE '%eventful%'
            	OR text LIKE '%everlasting%'
            	OR text LIKE '%evocative%'
            	OR text LIKE '%exalt%'
            	OR text LIKE '%exaltation%'
            	OR text LIKE '%exalted%'
            	OR text LIKE '%exaltedly%'
            	OR text LIKE '%exalting%'
            	OR text LIKE '%exaltingly%'
            	OR text LIKE '%examplar%'
            	OR text LIKE '%examplary%'
            	OR text LIKE '%excallent%'
            	OR text LIKE '%exceed%'
            	OR text LIKE '%exceeded%'
            	OR text LIKE '%exceeding%'
            	OR text LIKE '%exceedingly%'
            	OR text LIKE '%exceeds%'
            	OR text LIKE '%excel%'
            	OR text LIKE '%exceled%'
            	OR text LIKE '%excelent%'
            	OR text LIKE '%excellant%'
            	OR text LIKE '%excelled%'
            	OR text LIKE '%excellence%'
            	OR text LIKE '%excellency%'
            	OR text LIKE '%excellent%'
            	OR text LIKE '%excellently%'
            	OR text LIKE '%excels%'
            	OR text LIKE '%exceptional%'
            	OR text LIKE '%exceptionally%'
            	OR text LIKE '%excite%'
            	OR text LIKE '%excited%'
            	OR text LIKE '%excitedly%'
            	OR text LIKE '%excitedness%'
            	OR text LIKE '%excitement%'
            	OR text LIKE '%excites%'
            	OR text LIKE '%exciting%'
            	OR text LIKE '%excitingly%'
            	OR text LIKE '%exellent%'
            	OR text LIKE '%exemplar%'
            	OR text LIKE '%exemplary%'
            	OR text LIKE '%exhilarate%'
            	OR text LIKE '%exhilarating%'
            	OR text LIKE '%exhilaratingly%'
            	OR text LIKE '%exhilaration%'
            	OR text LIKE '%exonerate%'
            	OR text LIKE '%expansive%'
            	OR text LIKE '%expeditiously%'
            	OR text LIKE '%expertly%'
            	OR text LIKE '%exquisite%'
            	OR text LIKE '%exquisitely%'
            	OR text LIKE '%extol%'
            	OR text LIKE '%extoll%'
            	OR text LIKE '%extraordinarily%'
            	OR text LIKE '%extraordinary%'
            	OR text LIKE '%exuberance%'
            	OR text LIKE '%exuberant%'
            	OR text LIKE '%exuberantly%'
            	OR text LIKE '%exult%'
            	OR text LIKE '%exultant%'
            	OR text LIKE '%exultation%'
            	OR text LIKE '%exultingly%'
            	OR text LIKE '%eye-catch%'
            	OR text LIKE '%eye-catching%'
            	OR text LIKE '%eyecatch%'
            	OR text LIKE '%eyecatching%'
            	OR text LIKE '%fabulous%'
            	OR text LIKE '%fabulously%'
            	OR text LIKE '%facilitate%'
            	OR text LIKE '%fair%'
            	OR text LIKE '%fairly%'
            	OR text LIKE '%fairness%'
            	OR text LIKE '%faith%'
            	OR text LIKE '%faithful%'
            	OR text LIKE '%faithfully%'
            	OR text LIKE '%faithfulness%'
            	OR text LIKE '%fame%'
            	OR text LIKE '%famed%'
            	OR text LIKE '%famous%'
            	OR text LIKE '%famously%'
            	OR text LIKE '%fancier%'
            	OR text LIKE '%fancinating%'
            	OR text LIKE '%fancy%'
            	OR text LIKE '%fanfare%'
            	OR text LIKE '%fans%'
            	OR text LIKE '%fantastic%'
            	OR text LIKE '%fantastically%'
            	OR text LIKE '%fascinate%'
            	OR text LIKE '%fascinating%'
            	OR text LIKE '%fascinatingly%'
            	OR text LIKE '%fascination%'
            	OR text LIKE '%fashionable%'
            	OR text LIKE '%fashionably%'
            	OR text LIKE '%fast%'
            	OR text LIKE '%fast-growing%'
            	OR text LIKE '%fast-paced%'
            	OR text LIKE '%faster%'
            	OR text LIKE '%fastest%'
            	OR text LIKE '%fastest-growing%'
            	OR text LIKE '%faultless%'
            	OR text LIKE '%fav%'
            	OR text LIKE '%fave%'
            	OR text LIKE '%favor%'
            	OR text LIKE '%favorable%'
            	OR text LIKE '%favored%'
            	OR text LIKE '%favorite%'
            	OR text LIKE '%favorited%'
            	OR text LIKE '%favour%'
            	OR text LIKE '%fearless%'
            	OR text LIKE '%fearlessly%'
            	OR text LIKE '%feasible%'
            	OR text LIKE '%feasibly%'
            	OR text LIKE '%feat%'
            	OR text LIKE '%feature-rich%'
            	OR text LIKE '%fecilitous%'
            	OR text LIKE '%feisty%'
            	OR text LIKE '%felicitate%'
            	OR text LIKE '%felicitous%'
            	OR text LIKE '%felicity%'
            	OR text LIKE '%fertile%'
            	OR text LIKE '%fervent%'
            	OR text LIKE '%fervently%'
            	OR text LIKE '%fervid%'
            	OR text LIKE '%fervidly%'
            	OR text LIKE '%fervor%'
            	OR text LIKE '%festive%'
            	OR text LIKE '%fidelity%'
            	OR text LIKE '%fiery%'
            	OR text LIKE '%fine%'
            	OR text LIKE '%fine-looking%'
            	OR text LIKE '%finely%'
            	OR text LIKE '%finer%'
            	OR text LIKE '%finest%'
            	OR text LIKE '%firmer%'
            	OR text LIKE '%first-class%'
            	OR text LIKE '%first-in-class%'
            	OR text LIKE '%first-rate%'
            	OR text LIKE '%flashy%'
            	OR text LIKE '%flatter%'
            	OR text LIKE '%flattering%'
            	OR text LIKE '%flatteringly%'
            	OR text LIKE '%flawless%'
            	OR text LIKE '%flawlessly%'
            	OR text LIKE '%flexibility%'
            	OR text LIKE '%flexible%'
            	OR text LIKE '%flourish%'
            	OR text LIKE '%flourishing%'
            	OR text LIKE '%fluent%'
            	OR text LIKE '%flutter%'
            	OR text LIKE '%fond%'
            	OR text LIKE '%fondly%'
            	OR text LIKE '%fondness%'
            	OR text LIKE '%foolproof%'
            	OR text LIKE '%foremost%'
            	OR text LIKE '%foresight%'
            	OR text LIKE '%formidable%'
            	OR text LIKE '%fortitude%'
            	OR text LIKE '%fortuitous%'
            	OR text LIKE '%fortuitously%'
            	OR text LIKE '%fortunate%'
            	OR text LIKE '%fortunately%'
            	OR text LIKE '%fortune%'
            	OR text LIKE '%fragrant%'
            	OR text LIKE '%free%'
            	OR text LIKE '%freed%'
            	OR text LIKE '%freedom%'
            	OR text LIKE '%freedoms%'
            	OR text LIKE '%fresh%'
            	OR text LIKE '%fresher%'
            	OR text LIKE '%freshest%'
            	OR text LIKE '%friendliness%'
            	OR text LIKE '%friendly%'
            	OR text LIKE '%frolic%'
            	OR text LIKE '%frugal%'
            	OR text LIKE '%fruitful%'
            	OR text LIKE '%ftw%'
            	OR text LIKE '%fulfillment%'
            	OR text LIKE '%fun%'
            	OR text LIKE '%futurestic%'
            	OR text LIKE '%futuristic%'
            	OR text LIKE '%gaiety%'
            	OR text LIKE '%gaily%'
            	OR text LIKE '%gain%'
            	OR text LIKE '%gained%'
            	OR text LIKE '%gainful%'
            	OR text LIKE '%gainfully%'
            	OR text LIKE '%gaining%'
            	OR text LIKE '%gains%'
            	OR text LIKE '%gallant%'
            	OR text LIKE '%gallantly%'
            	OR text LIKE '%galore%'
            	OR text LIKE '%geekier%'
            	OR text LIKE '%geeky%'
            	OR text LIKE '%gem%'
            	OR text LIKE '%gems%'
            	OR text LIKE '%generosity%'
            	OR text LIKE '%generous%'
            	OR text LIKE '%generously%'
            	OR text LIKE '%genial%'
            	OR text LIKE '%genius%'
            	OR text LIKE '%gentle%'
            	OR text LIKE '%gentlest%'
            	OR text LIKE '%genuine%'
            	OR text LIKE '%gifted%'
            	OR text LIKE '%glad%'
            	OR text LIKE '%gladden%'
            	OR text LIKE '%gladly%'
            	OR text LIKE '%gladness%'
            	OR text LIKE '%glamorous%'
            	OR text LIKE '%glee%'
            	OR text LIKE '%gleeful%'
            	OR text LIKE '%gleefully%'
            	OR text LIKE '%glimmer%'
            	OR text LIKE '%glimmering%'
            	OR text LIKE '%glisten%'
            	OR text LIKE '%glistening%'
            	OR text LIKE '%glitter%'
            	OR text LIKE '%glitz%'
            	OR text LIKE '%glorify%'
            	OR text LIKE '%glorious%'
            	OR text LIKE '%gloriously%'
            	OR text LIKE '%glory%'
            	OR text LIKE '%glow%'
            	OR text LIKE '%glowing%'
            	OR text LIKE '%glowingly%'
            	OR text LIKE '%god-given%'
            	OR text LIKE '%god-send%'
            	OR text LIKE '%godlike%'
            	OR text LIKE '%godsend%'
            	OR text LIKE '%gold%'
            	OR text LIKE '%golden%'
            	OR text LIKE '%good%'
            	OR text LIKE '%goodly%'
            	OR text LIKE '%goodness%'
            	OR text LIKE '%goodwill%'
            	OR text LIKE '%goood%'
            	OR text LIKE '%gooood%'
            	OR text LIKE '%gorgeous%'
            	OR text LIKE '%gorgeously%'
            	OR text LIKE '%grace%'
            	OR text LIKE '%graceful%'
            	OR text LIKE '%gracefully%'
            	OR text LIKE '%gracious%'
            	OR text LIKE '%graciously%'
            	OR text LIKE '%graciousness%'
            	OR text LIKE '%grand%'
            	OR text LIKE '%grandeur%'
            	OR text LIKE '%grateful%'
            	OR text LIKE '%gratefully%'
            	OR text LIKE '%gratification%'
            	OR text LIKE '%gratified%'
            	OR text LIKE '%gratifies%'
            	OR text LIKE '%gratify%'
            	OR text LIKE '%gratifying%'
            	OR text LIKE '%gratifyingly%'
            	OR text LIKE '%gratitude%'
            	OR text LIKE '%great%'
            	OR text LIKE '%greatest%'
            	OR text LIKE '%greatness%'
            	OR text LIKE '%grin%'
            	OR text LIKE '%groundbreaking%'
            	OR text LIKE '%guarantee%'
            	OR text LIKE '%guidance%'
            	OR text LIKE '%guiltless%'
            	OR text LIKE '%gumption%'
            	OR text LIKE '%gush%'
            	OR text LIKE '%gusto%'
            	OR text LIKE '%gutsy%'
            	OR text LIKE '%hail%'
            	OR text LIKE '%halcyon%'
            	OR text LIKE '%hale%'
            	OR text LIKE '%hallmark%'
            	OR text LIKE '%hallmarks%'
            	OR text LIKE '%hallowed%'
            	OR text LIKE '%handier%'
            	OR text LIKE '%handily%'
            	OR text LIKE '%hands-down%'
            	OR text LIKE '%handsome%'
            	OR text LIKE '%handsomely%'
            	OR text LIKE '%handy%'
            	OR text LIKE '%happier%'
            	OR text LIKE '%happily%'
            	OR text LIKE '%happiness%'
            	OR text LIKE '%happy%'
            	OR text LIKE '%hard-working%'
            	OR text LIKE '%hardier%'
            	OR text LIKE '%hardy%'
            	OR text LIKE '%harmless%'
            	OR text LIKE '%harmonious%'
            	OR text LIKE '%harmoniously%'
            	OR text LIKE '%harmonize%'
            	OR text LIKE '%harmony%'
            	OR text LIKE '%headway%'
            	OR text LIKE '%heal%'
            	OR text LIKE '%healthful%'
            	OR text LIKE '%healthy%'
            	OR text LIKE '%hearten%'
            	OR text LIKE '%heartening%'
            	OR text LIKE '%heartfelt%'
            	OR text LIKE '%heartily%'
            	OR text LIKE '%heartwarming%'
            	OR text LIKE '%heaven%'
            	OR text LIKE '%heavenly%'
            	OR text LIKE '%helped%'
            	OR text LIKE '%helpful%'
            	OR text LIKE '%helping%'
            	OR text LIKE '%hero%'
            	OR text LIKE '%heroic%'
            	OR text LIKE '%heroically%'
            	OR text LIKE '%heroine%'
            	OR text LIKE '%heroize%'
            	OR text LIKE '%heros%'
            	OR text LIKE '%high-quality%'
            	OR text LIKE '%high-spirited%'
            	OR text LIKE '%hilarious%'
            	OR text LIKE '%holy%'
            	OR text LIKE '%homage%'
            	OR text LIKE '%honest%'
            	OR text LIKE '%honesty%'
            	OR text LIKE '%honor%'
            	OR text LIKE '%honorable%'
            	OR text LIKE '%honored%'
            	OR text LIKE '%honoring%'
            	OR text LIKE '%hooray%'
            	OR text LIKE '%hopeful%'
            	OR text LIKE '%hospitable%'
            	OR text LIKE '%hot%'
            	OR text LIKE '%hotcake%'
            	OR text LIKE '%hotcakes%'
            	OR text LIKE '%hottest%'
            	OR text LIKE '%hug%'
            	OR text LIKE '%humane%'
            	OR text LIKE '%humble%'
            	OR text LIKE '%humility%'
            	OR text LIKE '%humor%'
            	OR text LIKE '%humorous%'
            	OR text LIKE '%humorously%'
            	OR text LIKE '%humour%'
            	OR text LIKE '%humourous%'
            	OR text LIKE '%ideal%'
            	OR text LIKE '%idealize%'
            	OR text LIKE '%ideally%'
            	OR text LIKE '%idol%'
            	OR text LIKE '%idolize%'
            	OR text LIKE '%idolized%'
            	OR text LIKE '%idyllic%'
            	OR text LIKE '%illuminate%'
            	OR text LIKE '%illuminati%'
            	OR text LIKE '%illuminating%'
            	OR text LIKE '%illumine%'
            	OR text LIKE '%illustrious%'
            	OR text LIKE '%ilu%'
            	OR text LIKE '%imaculate%'
            	OR text LIKE '%imaginative%'
            	OR text LIKE '%immaculate%'
            	OR text LIKE '%immaculately%'
            	OR text LIKE '%immense%'
            	OR text LIKE '%impartial%'
            	OR text LIKE '%impartiality%'
            	OR text LIKE '%impartially%'
            	OR text LIKE '%impassioned%'
            	OR text LIKE '%impeccable%'
            	OR text LIKE '%impeccably%'
            	OR text LIKE '%important%'
            	OR text LIKE '%impress%'
            	OR text LIKE '%impressed%'
            	OR text LIKE '%impresses%'
            	OR text LIKE '%impressive%'
            	OR text LIKE '%impressively%'
            	OR text LIKE '%impressiveness%'
            	OR text LIKE '%improve%'
            	OR text LIKE '%improved%'
            	OR text LIKE '%improvement%'
            	OR text LIKE '%improvements%'
            	OR text LIKE '%improves%'
            	OR text LIKE '%improving%'
            	OR text LIKE '%incredible%'
            	OR text LIKE '%incredibly%'
            	OR text LIKE '%indebted%'
            	OR text LIKE '%individualized%'
            	OR text LIKE '%indulgence%'
            	OR text LIKE '%indulgent%'
            	OR text LIKE '%industrious%'
            	OR text LIKE '%inestimable%'
            	OR text LIKE '%inestimably%'
            	OR text LIKE '%inexpensive%'
            	OR text LIKE '%infallibility%'
            	OR text LIKE '%infallible%'
            	OR text LIKE '%infallibly%'
            	OR text LIKE '%influential%'
            	OR text LIKE '%ingenious%'
            	OR text LIKE '%ingeniously%'
            	OR text LIKE '%ingenuity%'
            	OR text LIKE '%ingenuous%'
            	OR text LIKE '%ingenuously%'
            	OR text LIKE '%innocuous%'
            	OR text LIKE '%innovation%'
            	OR text LIKE '%innovative%'
            	OR text LIKE '%inpressed%'
            	OR text LIKE '%insightful%'
            	OR text LIKE '%insightfully%'
            	OR text LIKE '%inspiration%'
            	OR text LIKE '%inspirational%'
            	OR text LIKE '%inspire%'
            	OR text LIKE '%inspiring%'
            	OR text LIKE '%instantly%'
            	OR text LIKE '%instructive%'
            	OR text LIKE '%instrumental%'
            	OR text LIKE '%integral%'
            	OR text LIKE '%integrated%'
            	OR text LIKE '%intelligence%'
            	OR text LIKE '%intelligent%'
            	OR text LIKE '%intelligible%'
            	OR text LIKE '%interesting%'
            	OR text LIKE '%interests%'
            	OR text LIKE '%intimacy%'
            	OR text LIKE '%intimate%'
            	OR text LIKE '%intricate%'
            	OR text LIKE '%intrigue%'
            	OR text LIKE '%intriguing%'
            	OR text LIKE '%intriguingly%'
            	OR text LIKE '%intuitive%'
            	OR text LIKE '%invaluable%'
            	OR text LIKE '%invaluablely%'
            	OR text LIKE '%inventive%'
            	OR text LIKE '%invigorate%'
            	OR text LIKE '%invigorating%'
            	OR text LIKE '%invincibility%'
            	OR text LIKE '%invincible%'
            	OR text LIKE '%inviolable%'
            	OR text LIKE '%inviolate%'
            	OR text LIKE '%invulnerable%'
            	OR text LIKE '%irreplaceable%'
            	OR text LIKE '%irreproachable%'
            	OR text LIKE '%irresistible%'
            	OR text LIKE '%irresistibly%'
            	OR text LIKE '%issue-free%'
            	OR text LIKE '%jaw-droping%'
            	OR text LIKE '%jaw-dropping%'
            	OR text LIKE '%jollify%'
            	OR text LIKE '%jolly%'
            	OR text LIKE '%jovial%'
            	OR text LIKE '%joy%'
            	OR text LIKE '%joyful%'
            	OR text LIKE '%joyfully%'
            	OR text LIKE '%joyous%'
            	OR text LIKE '%joyously%'
            	OR text LIKE '%jubilant%'
            	OR text LIKE '%jubilantly%'
            	OR text LIKE '%jubilate%'
            	OR text LIKE '%jubilation%'
            	OR text LIKE '%jubiliant%'
            	OR text LIKE '%judicious%'
            	OR text LIKE '%justly%'
            	OR text LIKE '%keen%'
            	OR text LIKE '%keenly%'
            	OR text LIKE '%keenness%'
            	OR text LIKE '%kid-friendly%'
            	OR text LIKE '%kindliness%'
            	OR text LIKE '%kindly%'
            	OR text LIKE '%kindness%'
            	OR text LIKE '%knowledgeable%'
            	OR text LIKE '%kudos%'
            	OR text LIKE '%large-capacity%'
            	OR text LIKE '%laud%'
            	OR text LIKE '%laudable%'
            	OR text LIKE '%laudably%'
            	OR text LIKE '%lavish%'
            	OR text LIKE '%lavishly%'
            	OR text LIKE '%law-abiding%'
            	OR text LIKE '%lawful%'
            	OR text LIKE '%lawfully%'
            	OR text LIKE '%lead%'
            	OR text LIKE '%leading%'
            	OR text LIKE '%leads%'
            	OR text LIKE '%lean%'
            	OR text LIKE '%led%'
            	OR text LIKE '%legendary%'
            	OR text LIKE '%leverage%'
            	OR text LIKE '%levity%'
            	OR text LIKE '%liberate%'
            	OR text LIKE '%liberation%'
            	OR text LIKE '%liberty%'
            	OR text LIKE '%lifesaver%'
            	OR text LIKE '%light-hearted%'
            	OR text LIKE '%lighter%'
            	OR text LIKE '%likable%'
            	OR text LIKE '%like%'
            	OR text LIKE '%liked%'
            	OR text LIKE '%likes%'
            	OR text LIKE '%liking%'
            	OR text LIKE '%lionhearted%'
            	OR text LIKE '%lively%'
            	OR text LIKE '%logical%'
            	OR text LIKE '%long-lasting%'
            	OR text LIKE '%lovable%'
            	OR text LIKE '%lovably%'
            	OR text LIKE '%love%'
            	OR text LIKE '%loved%'
            	OR text LIKE '%loveliness%'
            	OR text LIKE '%lovely%'
            	OR text LIKE '%lover%'
            	OR text LIKE '%loves%'
            	OR text LIKE '%loving%'
            	OR text LIKE '%low-cost%'
            	OR text LIKE '%low-price%'
            	OR text LIKE '%low-priced%'
            	OR text LIKE '%low-risk%'
            	OR text LIKE '%lower-priced%'
            	OR text LIKE '%loyal%'
            	OR text LIKE '%loyalty%'
            	OR text LIKE '%lucid%'
            	OR text LIKE '%lucidly%'
            	OR text LIKE '%luck%'
            	OR text LIKE '%luckier%'
            	OR text LIKE '%luckiest%'
            	OR text LIKE '%luckiness%'
            	OR text LIKE '%lucky%'
            	OR text LIKE '%lucrative%'
            	OR text LIKE '%luminous%'
            	OR text LIKE '%lush%'
            	OR text LIKE '%luster%'
            	OR text LIKE '%lustrous%'
            	OR text LIKE '%luxuriant%'
            	OR text LIKE '%luxuriate%'
            	OR text LIKE '%luxurious%'
            	OR text LIKE '%luxuriously%'
            	OR text LIKE '%luxury%'
            	OR text LIKE '%lyrical%'
            	OR text LIKE '%magic%'
            	OR text LIKE '%magical%'
            	OR text LIKE '%magnanimous%'
            	OR text LIKE '%magnanimously%'
            	OR text LIKE '%magnificence%'
            	OR text LIKE '%magnificent%'
            	OR text LIKE '%magnificently%'
            	OR text LIKE '%majestic%'
            	OR text LIKE '%majesty%'
            	OR text LIKE '%manageable%'
            	OR text LIKE '%maneuverable%'
            	OR text LIKE '%marvel%'
            	OR text LIKE '%marveled%'
            	OR text LIKE '%marvelled%'
            	OR text LIKE '%marvellous%'
            	OR text LIKE '%marvelous%'
            	OR text LIKE '%marvelously%'
            	OR text LIKE '%marvelousness%'
            	OR text LIKE '%marvels%'
            	OR text LIKE '%master%'
            	OR text LIKE '%masterful%'
            	OR text LIKE '%masterfully%'
            	OR text LIKE '%masterpiece%'
            	OR text LIKE '%masterpieces%'
            	OR text LIKE '%masters%'
            	OR text LIKE '%mastery%'
            	OR text LIKE '%matchless%'
            	OR text LIKE '%mature%'
            	OR text LIKE '%maturely%'
            	OR text LIKE '%maturity%'
            	OR text LIKE '%meaningful%'
            	OR text LIKE '%memorable%'
            	OR text LIKE '%merciful%'
            	OR text LIKE '%mercifully%'
            	OR text LIKE '%mercy%'
            	OR text LIKE '%merit%'
            	OR text LIKE '%meritorious%'
            	OR text LIKE '%merrily%'
            	OR text LIKE '%merriment%'
            	OR text LIKE '%merriness%'
            	OR text LIKE '%merry%'
            	OR text LIKE '%mesmerize%'
            	OR text LIKE '%mesmerized%'
            	OR text LIKE '%mesmerizes%'
            	OR text LIKE '%mesmerizing%'
            	OR text LIKE '%mesmerizingly%'
            	OR text LIKE '%meticulous%'
            	OR text LIKE '%meticulously%'
            	OR text LIKE '%mightily%'
            	OR text LIKE '%mighty%'
            	OR text LIKE '%mind-blowing%'
            	OR text LIKE '%miracle%'
            	OR text LIKE '%miracles%'
            	OR text LIKE '%miraculous%'
            	OR text LIKE '%miraculously%'
            	OR text LIKE '%miraculousness%'
            	OR text LIKE '%modern%'
            	OR text LIKE '%modest%'
            	OR text LIKE '%modesty%'
            	OR text LIKE '%momentous%'
            	OR text LIKE '%monumental%'
            	OR text LIKE '%monumentally%'
            	OR text LIKE '%morality%'
            	OR text LIKE '%motivated%'
            	OR text LIKE '%multi-purpose%'
            	OR text LIKE '%navigable%'
            	OR text LIKE '%neat%'
            	OR text LIKE '%neatest%'
            	OR text LIKE '%neatly%'
            	OR text LIKE '%nice%'
            	OR text LIKE '%nicely%'
            	OR text LIKE '%nicer%'
            	OR text LIKE '%nicest%'
            	OR text LIKE '%nifty%'
            	OR text LIKE '%nimble%'
            	OR text LIKE '%noble%'
            	OR text LIKE '%nobly%'
            	OR text LIKE '%noiseless%'
            	OR text LIKE '%non-violence%'
            	OR text LIKE '%non-violent%'
            	OR text LIKE '%notably%'
            	OR text LIKE '%noteworthy%'
            	OR text LIKE '%nourish%'
            	OR text LIKE '%nourishing%'
            	OR text LIKE '%nourishment%'
            	OR text LIKE '%novelty%'
            	OR text LIKE '%nurturing%'
            	OR text LIKE '%oasis%'
            	OR text LIKE '%obsession%'
            	OR text LIKE '%obsessions%'
            	OR text LIKE '%obtainable%'
            	OR text LIKE '%openly%'
            	OR text LIKE '%openness%'
            	OR text LIKE '%optimal%'
            	OR text LIKE '%optimism%'
            	OR text LIKE '%optimistic%'
            	OR text LIKE '%opulent%'
            	OR text LIKE '%orderly%'
            	OR text LIKE '%originality%'
            	OR text LIKE '%outdo%'
            	OR text LIKE '%outdone%'
            	OR text LIKE '%outperform%'
            	OR text LIKE '%outperformed%'
            	OR text LIKE '%outperforming%'
            	OR text LIKE '%outperforms%'
            	OR text LIKE '%outshine%'
            	OR text LIKE '%outshone%'
            	OR text LIKE '%outsmart%'
            	OR text LIKE '%outstanding%'
            	OR text LIKE '%outstandingly%'
            	OR text LIKE '%outstrip%'
            	OR text LIKE '%outwit%'
            	OR text LIKE '%ovation%'
            	OR text LIKE '%overjoyed%'
            	OR text LIKE '%overtake%'
            	OR text LIKE '%overtaken%'
            	OR text LIKE '%overtakes%'
            	OR text LIKE '%overtaking%'
            	OR text LIKE '%overtook%'
            	OR text LIKE '%overture%'
            	OR text LIKE '%pain-free%'
            	OR text LIKE '%painless%'
            	OR text LIKE '%painlessly%'
            	OR text LIKE '%palatial%'
            	OR text LIKE '%pamper%'
            	OR text LIKE '%pampered%'
            	OR text LIKE '%pamperedly%'
            	OR text LIKE '%pamperedness%'
            	OR text LIKE '%pampers%'
            	OR text LIKE '%panoramic%'
            	OR text LIKE '%paradise%'
            	OR text LIKE '%paramount%'
            	OR text LIKE '%pardon%'
            	OR text LIKE '%passion%'
            	OR text LIKE '%passionate%'
            	OR text LIKE '%passionately%'
            	OR text LIKE '%patience%'
            	OR text LIKE '%patient%'
            	OR text LIKE '%patiently%'
            	OR text LIKE '%patriot%'
            	OR text LIKE '%patriotic%'
            	OR text LIKE '%peace%'
            	OR text LIKE '%peaceable%'
            	OR text LIKE '%peaceful%'
            	OR text LIKE '%peacefully%'
            	OR text LIKE '%peacekeepers%'
            	OR text LIKE '%peach%'
            	OR text LIKE '%peerless%'
            	OR text LIKE '%pep%'
            	OR text LIKE '%pepped%'
            	OR text LIKE '%pepping%'
            	OR text LIKE '%peppy%'
            	OR text LIKE '%peps%'
            	OR text LIKE '%perfect%'
            	OR text LIKE '%perfection%'
            	OR text LIKE '%perfectly%'
            	OR text LIKE '%permissible%'
            	OR text LIKE '%perseverance%'
            	OR text LIKE '%persevere%'
            	OR text LIKE '%personages%'
            	OR text LIKE '%personalized%'
            	OR text LIKE '%phenomenal%'
            	OR text LIKE '%phenomenally%'
            	OR text LIKE '%picturesque%'
            	OR text LIKE '%piety%'
            	OR text LIKE '%pinnacle%'
            	OR text LIKE '%playful%'
            	OR text LIKE '%playfully%'
            	OR text LIKE '%pleasant%'
            	OR text LIKE '%pleasantly%'
            	OR text LIKE '%pleased%'
            	OR text LIKE '%pleases%'
            	OR text LIKE '%pleasing%'
            	OR text LIKE '%pleasingly%'
            	OR text LIKE '%pleasurable%'
            	OR text LIKE '%pleasurably%'
            	OR text LIKE '%pleasure%'
            	OR text LIKE '%plentiful%'
            	OR text LIKE '%pluses%'
            	OR text LIKE '%plush%'
            	OR text LIKE '%plusses%'
            	OR text LIKE '%poetic%'
            	OR text LIKE '%poeticize%'
            	OR text LIKE '%poignant%'
            	OR text LIKE '%poise%'
            	OR text LIKE '%poised%'
            	OR text LIKE '%polished%'
            	OR text LIKE '%polite%'
            	OR text LIKE '%politeness%'
            	OR text LIKE '%popular%'
            	OR text LIKE '%portable%'
            	OR text LIKE '%posh%'
            	OR text LIKE '%positive%'
            	OR text LIKE '%positively%'
            	OR text LIKE '%positives%'
            	OR text LIKE '%powerful%'
            	OR text LIKE '%powerfully%'
            	OR text LIKE '%praise%'
            	OR text LIKE '%praiseworthy%'
            	OR text LIKE '%praising%'
            	OR text LIKE '%pre-eminent%'
            	OR text LIKE '%precious%'
            	OR text LIKE '%precise%'
            	OR text LIKE '%precisely%'
            	OR text LIKE '%preeminent%'
            	OR text LIKE '%prefer%'
            	OR text LIKE '%preferable%'
            	OR text LIKE '%preferably%'
            	OR text LIKE '%prefered%'
            	OR text LIKE '%preferes%'
            	OR text LIKE '%preferring%'
            	OR text LIKE '%prefers%'
            	OR text LIKE '%premier%'
            	OR text LIKE '%prestige%'
            	OR text LIKE '%prestigious%'
            	OR text LIKE '%prettily%'
            	OR text LIKE '%pretty%'
            	OR text LIKE '%priceless%'
            	OR text LIKE '%pride%'
            	OR text LIKE '%principled%'
            	OR text LIKE '%privilege%'
            	OR text LIKE '%privileged%'
            	OR text LIKE '%prize%'
            	OR text LIKE '%proactive%'
            	OR text LIKE '%problem-free%'
            	OR text LIKE '%problem-solver%'
            	OR text LIKE '%prodigious%'
            	OR text LIKE '%prodigiously%'
            	OR text LIKE '%prodigy%'
            	OR text LIKE '%productive%'
            	OR text LIKE '%productively%'
            	OR text LIKE '%proficient%'
            	OR text LIKE '%proficiently%'
            	OR text LIKE '%profound%'
            	OR text LIKE '%profoundly%'
            	OR text LIKE '%profuse%'
            	OR text LIKE '%profusion%'
            	OR text LIKE '%progress%'
            	OR text LIKE '%progressive%'
            	OR text LIKE '%prolific%'
            	OR text LIKE '%prominence%'
            	OR text LIKE '%prominent%'
            	OR text LIKE '%promise%'
            	OR text LIKE '%promised%'
            	OR text LIKE '%promises%'
            	OR text LIKE '%promising%'
            	OR text LIKE '%promoter%'
            	OR text LIKE '%prompt%'
            	OR text LIKE '%promptly%'
            	OR text LIKE '%proper%'
            	OR text LIKE '%properly%'
            	OR text LIKE '%propitious%'
            	OR text LIKE '%propitiously%'
            	OR text LIKE '%pros%'
            	OR text LIKE '%prosper%'
            	OR text LIKE '%prosperity%'
            	OR text LIKE '%prosperous%'
            	OR text LIKE '%prospros%'
            	OR text LIKE '%protect%'
            	OR text LIKE '%protection%'
            	OR text LIKE '%protective%'
            	OR text LIKE '%proud%'
            	OR text LIKE '%proven%'
            	OR text LIKE '%proves%'
            	OR text LIKE '%providence%'
            	OR text LIKE '%proving%'
            	OR text LIKE '%prowess%'
            	OR text LIKE '%prudence%'
            	OR text LIKE '%prudent%'
            	OR text LIKE '%prudently%'
            	OR text LIKE '%punctual%'
            	OR text LIKE '%pure%'
            	OR text LIKE '%purify%'
            	OR text LIKE '%purposeful%'
            	OR text LIKE '%quaint%'
            	OR text LIKE '%qualified%'
            	OR text LIKE '%qualify%'
            	OR text LIKE '%quicker%'
            	OR text LIKE '%quiet%'
            	OR text LIKE '%quieter%'
            	OR text LIKE '%radiance%'
            	OR text LIKE '%radiant%'
            	OR text LIKE '%rapid%'
            	OR text LIKE '%rapport%'
            	OR text LIKE '%rapt%'
            	OR text LIKE '%rapture%'
            	OR text LIKE '%raptureous%'
            	OR text LIKE '%raptureously%'
            	OR text LIKE '%rapturous%'
            	OR text LIKE '%rapturously%'
            	OR text LIKE '%rational%'
            	OR text LIKE '%razor-sharp%'
            	OR text LIKE '%reachable%'
            	OR text LIKE '%readable%'
            	OR text LIKE '%readily%'
            	OR text LIKE '%ready%'
            	OR text LIKE '%reaffirm%'
            	OR text LIKE '%reaffirmation%'
            	OR text LIKE '%realistic%'
            	OR text LIKE '%realizable%'
            	OR text LIKE '%reasonable%'
            	OR text LIKE '%reasonably%'
            	OR text LIKE '%reasoned%'
            	OR text LIKE '%reassurance%'
            	OR text LIKE '%reassure%'
            	OR text LIKE '%receptive%'
            	OR text LIKE '%reclaim%'
            	OR text LIKE '%recomend%'
            	OR text LIKE '%recommend%'
            	OR text LIKE '%recommendation%'
            	OR text LIKE '%recommendations%'
            	OR text LIKE '%recommended%'
            	OR text LIKE '%reconcile%'
            	OR text LIKE '%reconciliation%'
            	OR text LIKE '%record-setting%'
            	OR text LIKE '%recover%'
            	OR text LIKE '%recovery%'
            	OR text LIKE '%rectification%'
            	OR text LIKE '%rectify%'
            	OR text LIKE '%rectifying%'
            	OR text LIKE '%redeem%'
            	OR text LIKE '%redeeming%'
            	OR text LIKE '%redemption%'
            	OR text LIKE '%refine%'
            	OR text LIKE '%refined%'
            	OR text LIKE '%refinement%'
            	OR text LIKE '%reform%'
            	OR text LIKE '%reformed%'
            	OR text LIKE '%reforming%'
            	OR text LIKE '%reforms%'
            	OR text LIKE '%refresh%'
            	OR text LIKE '%refreshed%'
            	OR text LIKE '%refreshing%'
            	OR text LIKE '%refund%'
            	OR text LIKE '%refunded%'
            	OR text LIKE '%regal%'
            	OR text LIKE '%regally%'
            	OR text LIKE '%regard%'
            	OR text LIKE '%rejoice%'
            	OR text LIKE '%rejoicing%'
            	OR text LIKE '%rejoicingly%'
            	OR text LIKE '%rejuvenate%'
            	OR text LIKE '%rejuvenated%'
            	OR text LIKE '%rejuvenating%'
            	OR text LIKE '%relaxed%'
            	OR text LIKE '%relent%'
            	OR text LIKE '%reliable%'
            	OR text LIKE '%reliably%'
            	OR text LIKE '%relief%'
            	OR text LIKE '%relish%'
            	OR text LIKE '%remarkable%'
            	OR text LIKE '%remarkably%'
            	OR text LIKE '%remedy%'
            	OR text LIKE '%remission%'
            	OR text LIKE '%remunerate%'
            	OR text LIKE '%renaissance%'
            	OR text LIKE '%renewed%'
            	OR text LIKE '%renown%'
            	OR text LIKE '%renowned%'
            	OR text LIKE '%replaceable%'
            	OR text LIKE '%reputable%'
            	OR text LIKE '%reputation%'
            	OR text LIKE '%resilient%'
            	OR text LIKE '%resolute%'
            	OR text LIKE '%resound%'
            	OR text LIKE '%resounding%'
            	OR text LIKE '%resourceful%'
            	OR text LIKE '%resourcefulness%'
            	OR text LIKE '%respect%'
            	OR text LIKE '%respectable%'
            	OR text LIKE '%respectful%'
            	OR text LIKE '%respectfully%'
            	OR text LIKE '%respite%'
            	OR text LIKE '%resplendent%'
            	OR text LIKE '%responsibly%'
            	OR text LIKE '%responsive%'
            	OR text LIKE '%restful%'
            	OR text LIKE '%restored%'
            	OR text LIKE '%restructure%'
            	OR text LIKE '%restructured%'
            	OR text LIKE '%restructuring%'
            	OR text LIKE '%retractable%'
            	OR text LIKE '%revel%'
            	OR text LIKE '%revelation%'
            	OR text LIKE '%revere%'
            	OR text LIKE '%reverence%'
            	OR text LIKE '%reverent%'
            	OR text LIKE '%reverently%'
            	OR text LIKE '%revitalize%'
            	OR text LIKE '%revival%'
            	OR text LIKE '%revive%'
            	OR text LIKE '%revives%'
            	OR text LIKE '%revolutionary%'
            	OR text LIKE '%revolutionize%'
            	OR text LIKE '%revolutionized%'
            	OR text LIKE '%revolutionizes%'
            	OR text LIKE '%reward%'
            	OR text LIKE '%rewarding%'
            	OR text LIKE '%rewardingly%'
            	OR text LIKE '%rich%'
            	OR text LIKE '%richer%'
            	OR text LIKE '%richly%'
            	OR text LIKE '%richness%'
            	OR text LIKE '%right%'
            	OR text LIKE '%righten%'
            	OR text LIKE '%righteous%'
            	OR text LIKE '%righteously%'
            	OR text LIKE '%righteousness%'
            	OR text LIKE '%rightful%'
            	OR text LIKE '%rightfully%'
            	OR text LIKE '%rightly%'
            	OR text LIKE '%rightness%'
            	OR text LIKE '%risk-free%'
            	OR text LIKE '%robust%'
            	OR text LIKE '%rock-star%'
            	OR text LIKE '%rock-stars%'
            	OR text LIKE '%rockstar%'
            	OR text LIKE '%rockstars%'
            	OR text LIKE '%romantic%'
            	OR text LIKE '%romantically%'
            	OR text LIKE '%romanticize%'
            	OR text LIKE '%roomier%'
            	OR text LIKE '%roomy%'
            	OR text LIKE '%rosy%'
            	OR text LIKE '%safe%'
            	OR text LIKE '%safely%'
            	OR text LIKE '%sagacity%'
            	OR text LIKE '%sagely%'
            	OR text LIKE '%saint%'
            	OR text LIKE '%saintliness%'
            	OR text LIKE '%saintly%'
            	OR text LIKE '%salutary%'
            	OR text LIKE '%salute%'
            	OR text LIKE '%sane%'
            	OR text LIKE '%satisfactorily%'
            	OR text LIKE '%satisfactory%'
            	OR text LIKE '%satisfied%'
            	OR text LIKE '%satisfies%'
            	OR text LIKE '%satisfy%'
            	OR text LIKE '%satisfying%'
            	OR text LIKE '%satisified%'
            	OR text LIKE '%saver%'
            	OR text LIKE '%savings%'
            	OR text LIKE '%savior%'
            	OR text LIKE '%savvy%'
            	OR text LIKE '%scenic%'
            	OR text LIKE '%seamless%'
            	OR text LIKE '%seasoned%'
            	OR text LIKE '%secure%'
            	OR text LIKE '%securely%'
            	OR text LIKE '%selective%'
            	OR text LIKE '%self-determination%'
            	OR text LIKE '%self-respect%'
            	OR text LIKE '%self-satisfaction%'
            	OR text LIKE '%self-sufficiency%'
            	OR text LIKE '%self-sufficient%'
            	OR text LIKE '%sensation%'
            	OR text LIKE '%sensational%'
            	OR text LIKE '%sensationally%'
            	OR text LIKE '%sensations%'
            	OR text LIKE '%sensible%'
            	OR text LIKE '%sensibly%'
            	OR text LIKE '%sensitive%'
            	OR text LIKE '%serene%'
            	OR text LIKE '%serenity%'
            	OR text LIKE '%sexy%'
            	OR text LIKE '%sharp%'
            	OR text LIKE '%sharper%'
            	OR text LIKE '%sharpest%'
            	OR text LIKE '%shimmering%'
            	OR text LIKE '%shimmeringly%'
            	OR text LIKE '%shine%'
            	OR text LIKE '%shiny%'
            	OR text LIKE '%significant%'
            	OR text LIKE '%silent%'
            	OR text LIKE '%simpler%'
            	OR text LIKE '%simplest%'
            	OR text LIKE '%simplified%'
            	OR text LIKE '%simplifies%'
            	OR text LIKE '%simplify%'
            	OR text LIKE '%simplifying%'
            	OR text LIKE '%sincere%'
            	OR text LIKE '%sincerely%'
            	OR text LIKE '%sincerity%'
            	OR text LIKE '%skill%'
            	OR text LIKE '%skilled%'
            	OR text LIKE '%skillful%'
            	OR text LIKE '%skillfully%'
            	OR text LIKE '%slammin%'
            	OR text LIKE '%sleek%'
            	OR text LIKE '%slick%'
            	OR text LIKE '%smart%'
            	OR text LIKE '%smarter%'
            	OR text LIKE '%smartest%'
            	OR text LIKE '%smartly%'
            	OR text LIKE '%smile%'
            	OR text LIKE '%smiles%'
            	OR text LIKE '%smiling%'
            	OR text LIKE '%smilingly%'
            	OR text LIKE '%smitten%'
            	OR text LIKE '%smooth%'
            	OR text LIKE '%smoother%'
            	OR text LIKE '%smoothes%'
            	OR text LIKE '%smoothest%'
            	OR text LIKE '%smoothly%'
            	OR text LIKE '%snappy%'
            	OR text LIKE '%snazzy%'
            	OR text LIKE '%sociable%'
            	OR text LIKE '%soft%'
            	OR text LIKE '%softer%'
            	OR text LIKE '%solace%'
            	OR text LIKE '%solicitous%'
            	OR text LIKE '%solicitously%'
            	OR text LIKE '%solid%'
            	OR text LIKE '%solidarity%'
            	OR text LIKE '%soothe%'
            	OR text LIKE '%soothingly%'
            	OR text LIKE '%sophisticated%'
            	OR text LIKE '%soulful%'
            	OR text LIKE '%soundly%'
            	OR text LIKE '%soundness%'
            	OR text LIKE '%spacious%'
            	OR text LIKE '%sparkle%'
            	OR text LIKE '%sparkling%'
            	OR text LIKE '%spectacular%'
            	OR text LIKE '%spectacularly%'
            	OR text LIKE '%speedily%'
            	OR text LIKE '%speedy%'
            	OR text LIKE '%spellbind%'
            	OR text LIKE '%spellbinding%'
            	OR text LIKE '%spellbindingly%'
            	OR text LIKE '%spellbound%'
            	OR text LIKE '%spirited%'
            	OR text LIKE '%spiritual%'
            	OR text LIKE '%splendid%'
            	OR text LIKE '%splendidly%'
            	OR text LIKE '%splendor%'
            	OR text LIKE '%spontaneous%'
            	OR text LIKE '%sporty%'
            	OR text LIKE '%spotless%'
            	OR text LIKE '%sprightly%'
            	OR text LIKE '%stability%'
            	OR text LIKE '%stabilize%'
            	OR text LIKE '%stable%'
            	OR text LIKE '%stainless%'
            	OR text LIKE '%standout%'
            	OR text LIKE '%state-of-the-art%'
            	OR text LIKE '%stately%'
            	OR text LIKE '%statuesque%'
            	OR text LIKE '%staunch%'
            	OR text LIKE '%staunchly%'
            	OR text LIKE '%staunchness%'
            	OR text LIKE '%steadfast%'
            	OR text LIKE '%steadfastly%'
            	OR text LIKE '%steadfastness%'
            	OR text LIKE '%steadiest%'
            	OR text LIKE '%steadiness%'
            	OR text LIKE '%steady%'
            	OR text LIKE '%stellar%'
            	OR text LIKE '%stellarly%'
            	OR text LIKE '%stimulate%'
            	OR text LIKE '%stimulates%'
            	OR text LIKE '%stimulating%'
            	OR text LIKE '%stimulative%'
            	OR text LIKE '%stirringly%'
            	OR text LIKE '%straighten%'
            	OR text LIKE '%straightforward%'
            	OR text LIKE '%streamlined%'
            	OR text LIKE '%striking%'
            	OR text LIKE '%strikingly%'
            	OR text LIKE '%striving%'
            	OR text LIKE '%strong%'
            	OR text LIKE '%stronger%'
            	OR text LIKE '%strongest%'
            	OR text LIKE '%stunned%'
            	OR text LIKE '%stunning%'
            	OR text LIKE '%stunningly%'
            	OR text LIKE '%stupendous%'
            	OR text LIKE '%stupendously%'
            	OR text LIKE '%sturdier%'
            	OR text LIKE '%sturdy%'
            	OR text LIKE '%stylish%'
            	OR text LIKE '%stylishly%'
            	OR text LIKE '%stylized%'
            	OR text LIKE '%suave%'
            	OR text LIKE '%suavely%'
            	OR text LIKE '%sublime%'
            	OR text LIKE '%subsidize%'
            	OR text LIKE '%subsidized%'
            	OR text LIKE '%subsidizes%'
            	OR text LIKE '%subsidizing%'
            	OR text LIKE '%substantive%'
            	OR text LIKE '%succeed%'
            	OR text LIKE '%succeeded%'
            	OR text LIKE '%succeeding%'
            	OR text LIKE '%succeeds%'
            	OR text LIKE '%succes%'
            	OR text LIKE '%success%'
            	OR text LIKE '%successes%'
            	OR text LIKE '%successful%'
            	OR text LIKE '%successfully%'
            	OR text LIKE '%suffice%'
            	OR text LIKE '%sufficed%'
            	OR text LIKE '%suffices%'
            	OR text LIKE '%sufficient%'
            	OR text LIKE '%sufficiently%'
            	OR text LIKE '%suitable%'
            	OR text LIKE '%sumptuous%'
            	OR text LIKE '%sumptuously%'
            	OR text LIKE '%sumptuousness%'
            	OR text LIKE '%super%'
            	OR text LIKE '%superb%'
            	OR text LIKE '%superbly%'
            	OR text LIKE '%superior%'
            	OR text LIKE '%superiority%'
            	OR text LIKE '%supple%'
            	OR text LIKE '%support%'
            	OR text LIKE '%supported%'
            	OR text LIKE '%supporter%'
            	OR text LIKE '%supporting%'
            	OR text LIKE '%supportive%'
            	OR text LIKE '%supports%'
            	OR text LIKE '%supremacy%'
            	OR text LIKE '%supreme%'
            	OR text LIKE '%supremely%'
            	OR text LIKE '%supurb%'
            	OR text LIKE '%supurbly%'
            	OR text LIKE '%surmount%'
            	OR text LIKE '%surpass%'
            	OR text LIKE '%surreal%'
            	OR text LIKE '%survival%'
            	OR text LIKE '%survivor%'
            	OR text LIKE '%sustainability%'
            	OR text LIKE '%sustainable%'
            	OR text LIKE '%swank%'
            	OR text LIKE '%swankier%'
            	OR text LIKE '%swankiest%'
            	OR text LIKE '%swanky%'
            	OR text LIKE '%sweeping%'
            	OR text LIKE '%sweet%'
            	OR text LIKE '%sweeten%'
            	OR text LIKE '%sweetheart%'
            	OR text LIKE '%sweetly%'
            	OR text LIKE '%sweetness%'
            	OR text LIKE '%swift%'
            	OR text LIKE '%swiftness%'
            	OR text LIKE '%talent%'
            	OR text LIKE '%talented%'
            	OR text LIKE '%talents%'
            	OR text LIKE '%tantalize%'
            	OR text LIKE '%tantalizing%'
            	OR text LIKE '%tantalizingly%'
            	OR text LIKE '%tempt%'
            	OR text LIKE '%tempting%'
            	OR text LIKE '%temptingly%'
            	OR text LIKE '%tenacious%'
            	OR text LIKE '%tenaciously%'
            	OR text LIKE '%tenacity%'
            	OR text LIKE '%tender%'
            	OR text LIKE '%tenderly%'
            	OR text LIKE '%terrific%'
            	GROUP BY business_id
            ) as t1 ,
            businesstable, categoriestable
            where t1.business_id = businesstable.business_id and categoriestable.business_id = t1.business_id and  businesstable.postal_code='""" +zipcode+ """' AND categoriestable.category_name= '"""+category+"""' 
            ORDER BY t1.score desc;
            """
        for i in reversed(range(self.ui.bustable1.rowCount())):
            self.ui.bustable1.removeRow(i)
        try:
            results = self.executeQuery(sql_str)
            style = "::section {""background-color: #f3f3f3; }"
            self.ui.bustable1.horizontalHeader().setStyleSheet(style)
            self.ui.bustable1.setColumnCount(len(results[0]))
            self.ui.bustable1.setRowCount(len(results))
            self.ui.bustable1.setHorizontalHeaderLabels(['Name', '# of Checkins', '# of Tips', 'Popularity Score'])
            self.ui.bustable1.resizeColumnsToContents()
            self.ui.bustable1.setColumnWidth(0,300)
            self.ui.bustable1.setColumnWidth(1,40)
            self.ui.bustable1.setColumnWidth(2,40)
            self.ui.bustable1.setColumnWidth(3,40)
            currentRowCount = 0
            for row in results:
                for colCount in range (0,len(results[0])):
                    if type(row[colCount]) == str:
                        self.ui.bustable1.setItem(currentRowCount,colCount,QTableWidgetItem(row[colCount]))
                    else:
                        self.ui.bustable1.setItem(currentRowCount,colCount,QTableWidgetItem(str(row[colCount])))                    
                currentRowCount +=1
        except:
            print("Query failed")
        for i in reversed(range(self.ui.bustable2.rowCount())):
            self.ui.bustable2.removeRow(i)
        try:
            results = self.executeQuery(sql_str2)
            style = "::section {""background-color: #f3f3f3; }"
            self.ui.bustable2.horizontalHeader().setStyleSheet(style)
            self.ui.bustable2.setColumnCount(len(results[0]))
            self.ui.bustable2.setRowCount(len(results))
            self.ui.bustable2.setHorizontalHeaderLabels(['Name', 'Address', 'Score'])
            self.ui.bustable2.resizeColumnsToContents()
            self.ui.bustable2.setColumnWidth(0,250)
            self.ui.bustable2.setColumnWidth(1,200)
            self.ui.bustable2.setColumnWidth(2,50)
            currentRowCount = 0
            for row in results:
                for colCount in range (0,len(results[0])):
                    if type(row[colCount]) == str:
                        self.ui.bustable2.setItem(currentRowCount,colCount,QTableWidgetItem(row[colCount]))
                    else:
                        self.ui.bustable2.setItem(currentRowCount,colCount,QTableWidgetItem(str(row[colCount])))
                currentRowCount +=1
        except:
            print("Query failed")
        
        
if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = milestone1()
    window.show()
    sys.exit(app.exec_())
